# Generated by Django 4.1.7 on 2023-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0002_destinationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproductdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pn', models.CharField(blank=True, max_length=50, null=True)),
                ('pr', models.IntegerField(blank=True, null=True)),
                ('ds', models.CharField(blank=True, max_length=50, null=True)),
                ('pi', models.ImageField(blank=True, null=True, upload_to='pr cosmetics')),
            ],
        ),
    ]
