# Generated by Django 4.1.7 on 2023-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Cnum', models.IntegerField(blank=True, null=True)),
                ('Expdate', models.IntegerField(blank=True, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Bemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Add', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.CharField(blank=True, max_length=100, null=True)),
                ('Cname', models.CharField(blank=True, max_length=100, null=True)),
                ('Cnum', models.IntegerField(blank=True, null=True)),
                ('Expm', models.CharField(blank=True, max_length=100, null=True)),
                ('Expyear', models.IntegerField(blank=True, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='users',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='des_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
