# Generated by Django 4.1.7 on 2023-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_card_checkout_remove_history_user_history_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('msg', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
