# Generated by Django 4.1.7 on 2023-08-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationdb',
            name='emails',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
