# Generated by Django 4.1.7 on 2023-08-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_userregistrationdb_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationdb',
            old_name='emails',
            new_name='uemail',
        ),
        migrations.AddField(
            model_name='userregistrationdb',
            name='umob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
